package com.whalegirl.pet;
import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.util.DisplayMetrics;import java.util.*;
public class PetOverlayService extends Service{
 WindowManager wm; WindowManager.LayoutParams lp; PetView pet; final String ch="whale_pet";
 @Override public void onCreate(){super.onCreate();NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)nm.createNotificationChannel(new NotificationChannel(ch,"鲸鱼娘桌宠",NotificationManager.IMPORTANCE_LOW));startForeground(7,new Notification.Builder(this,ch).setContentTitle("鲸鱼娘正在桌面活动").setContentText("拖动她，松手后会掉下来哦").setSmallIcon(android.R.drawable.ic_menu_compass).build());wm=(WindowManager)getSystemService(WINDOW_SERVICE);lp=new WindowManager.LayoutParams(330,420,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);lp.gravity=Gravity.TOP|Gravity.START;lp.x=120;lp.y=120;pet=new PetView(this);wm.addView(pet,lp);}
 @Override public int onStartCommand(Intent i,int f,int id){if(i!=null&&i.getStringExtra("speak")!=null&&pet!=null)pet.say(i.getStringExtra("speak"));return START_STICKY;}
 @Override public void onDestroy(){if(pet!=null)try{wm.removeView(pet);}catch(Exception ignored){}super.onDestroy();}
 @Override public android.os.IBinder onBind(Intent i){return null;}
 class PetView extends View{
  Paint p=new Paint(1),tp=new Paint(1);float wx=120,wy=120,vx,vy;boolean drag=false,anim=false;float rx,ry;long lt;String bubble=null;long bubbleUntil=0;Random rnd=new Random();String[] dragLines={"欸——！","轻一点嘛！","尾巴要打结啦…","我不是挂件啦！"};String[] hitLines={"啪叽。","……你是不是故意的。","地板今天也很硬呢。"};
  PetView(Context c){super(c);tp.setColor(Color.rgb(48,62,98));tp.setTextSize(28);tp.setTextAlign(Paint.Align.CENTER);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
  void say(String s){bubble=s;bubbleUntil=SystemClock.uptimeMillis()+4000;invalidate();}
  protected void onDraw(Canvas c){super.onDraw(c);float t=SystemClock.uptimeMillis()/1000f,cx=getWidth()/2f,cy=getHeight()*.57f;float bob=drag?0:(float)Math.sin(t*2.2)*5;c.save();c.translate(cx,cy+bob);float flap=(float)Math.sin(t*(drag?18:3))*12;p.setColor(Color.rgb(75,116,210));Path tail=new Path();tail.moveTo(-10,80);tail.cubicTo(-50,110,-80,150,-55,185);tail.lineTo(-110,175);tail.lineTo(-78,220);tail.lineTo(-25,185);tail.cubicTo(0,150,15,110,10,80);tail.close();c.drawPath(tail,p);p.setColor(Color.rgb(88,128,220));c.drawOval(-95,-112,95,105,p);p.setColor(Color.rgb(242,247,255));c.drawOval(-68,-60,68,82,p);p.setColor(Color.rgb(93,137,229));c.save();c.rotate(-8+flap,-82,-35);c.drawOval(-132,-55,-66,-10,p);c.restore();c.save();c.rotate(8-flap,82,-35);c.drawOval(66,-55,132,-10,p);c.restore();p.setColor(Color.rgb(50,72,130));c.drawOval(-38,-29,-22,-10,p);c.drawOval(22,-29,38,-10,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);c.drawArc(-25,0,25,32,10,160,false,p);p.setStyle(Paint.Style.FILL);c.restore();if(bubble!=null&&SystemClock.uptimeMillis()<bubbleUntil){p.setColor(Color.argb(240,255,255,255));c.drawRoundRect(10,8,getWidth()-10,60,22,22,p);c.drawText(bubble,getWidth()/2f,43,tp);} }
  public boolean onTouchEvent(MotionEvent e){switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:drag=true;anim=false;vx=vy=0;rx=e.getRawX();ry=e.getRawY();lt=System.nanoTime();if(rnd.nextFloat()<.25)say(dragLines[rnd.nextInt(dragLines.length)]);return true;case MotionEvent.ACTION_MOVE:long n=System.nanoTime();float dt=Math.max(.001f,(n-lt)/1_000_000_000f),dx=e.getRawX()-rx,dy=e.getRawY()-ry;wx+=dx;wy+=dy;vx=Math.max(-5000,Math.min(5000,dx/dt));vy=Math.max(-5000,Math.min(5000,dy/dt));rx=e.getRawX();ry=e.getRawY();lt=n;lp.x=Math.round(wx);lp.y=Math.round(wy);wm.updateViewLayout(this,lp);invalidate();return true;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:drag=false;startPhysics();return true;}return true;}
  void startPhysics(){if(anim)return;anim=true;final long[] last={System.nanoTime()};final Choreographer ch=Choreographer.getInstance();final Choreographer.FrameCallback[] cb=new Choreographer.FrameCallback[1];cb[0]=n->{if(!anim||drag)return;float dt=Math.max(.001f,Math.min(.033f,(n-last[0])/1_000_000_000f));last[0]=n;DisplayMetrics dm=getResources().getDisplayMetrics();float maxX=Math.max(0,dm.widthPixels-getWidth()),maxY=Math.max(0,dm.heightPixels-getHeight());vy+=2600*dt;vx*=Math.pow(.992,dt*60);wx+=vx*dt;wy+=vy*dt;if(wx<0){wx=0;vx=Math.abs(vx)*.58f;}else if(wx>maxX){wx=maxX;vx=-Math.abs(vx)*.58f;}if(wy<0){wy=0;vy=Math.abs(vy)*.58f;}if(wy>maxY){float imp=Math.abs(vy);wy=maxY;vy=-imp*.58f;vx*=.82f;if(imp>900&&rnd.nextFloat()<.3)say(hitLines[rnd.nextInt(hitLines.length)]);}lp.x=Math.round(wx);lp.y=Math.round(wy);wm.updateViewLayout(this,lp);if(wy>=maxY-1&&Math.abs(vy)<55&&Math.abs(vx)<35){anim=false;vx=vy=0;}else ch.postFrameCallback(cb[0]);};ch.postFrameCallback(cb[0]);}
 }
}
